# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 916f2c3f7de9a4d61ab50d630e2ed4c02fa3250e0dc32da2bf9f252de9506fca7dad265363ee14ee5b9ecd13e83a98ea204f1052e38e0925bc60480b8dc327dc

test:
  secret_key_base: ced99e895540241e5026bf5cd3e15e6275748cd050cdf75d444c4fcb7f97b8aa2a632221afc80edd90c661a6131a3b59e4267fae873d7cf6ba1a81cca2e83329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
