# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1b8b27eb151fa2cd1b2c4d4f3dde29082c9edda141a7ea8f14fa32b439975b16770ee8999c49f5e7761983a64c9d6ce6a7cd3a5dab0fc921ac134883964f045

test:
  secret_key_base: 2aa89f75161868399f82fc1b55d3ebdc7f03acc755d77b3a25909ea70b55b095773ed5b92df29df5515af48851b1f48a9b5bcb56a4dccde96cc75163a349a116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
