# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40d85f65c7936f56f46d20889ce6258e207c98e8a1946a8d0b93ba5aae6323d2cd246aab60574e355ffebf2139eb7130633b67b0a18245d45368c26a47dd9c8e

test:
  secret_key_base: 9bf6bc7918ce113cbd82a3d3e1dae1eec407aaa8682b50b39e134ee700a8613894f17b96f30cead21738ce3ffa510fd534e857a6f70887ecb8a743cb49a521c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
