# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78072ce156a212042a4abd454491922a4cdd5827108f535278ce2e582f01e94a6c9293ddb60dc8418db415a2aa30aa0c4e320a9f6c472e9496ab265fbd30fe48

test:
  secret_key_base: 6da091ad7cd9cda0add6965432d25e02e56dd82c6d7e072400470758be654a7e89ca56d5751ec89dd39a0df8455cdce6882b12a69fab3b309228ed95f5118098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
