# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bc5fe49941ff186946f3d62eee35a61f5774059d279d4ca55f33c5bcadec48f7df0c7cd105010fedd423d8fcabfacc59271b6ed8ccee68d995f513e999b5575

test:
  secret_key_base: f24e36602abd419db9b2edc9b6a6387de9591d3cc6ee7a94c7202d30143848470f54f0e15e98ad898b5f7e96709c39815fa89d06a90fd8cd9adb6cd515568bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
